routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
//    return redirect()->route('login');
});

Route::middleware(['auth'])->group(function () {

    Route::get('index', function (){
        return view('index');
    })->name('home.index');

    ///// Super admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'super_admin'], function (){

        Route::resources([
            'admin'=>\App\Http\Controllers\AdminController::class]);

    });

    ///// Admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'admin'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'index', 'show','edit','update'
        ]);

    });

    ///// Manager routes /////
    Route::group(['prefix'=>'admin','middleware'=>'manager'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'show','edit','index'
        ]);

        Route::resource('buyer', \App\Http\Controllers\BuyerController::class)->only([
            'index'
        ]);
    });


    Route::resource('dashboard',\App\Http\Controllers\DashboardController::class);
    Route::resource('phone',\App\Http\Controllers\PhoneNumberController::class);
    Route::resource('sms',\App\Http\Controllers\SmsController::class);
    Route::resource('sms_service',\App\Http\Controllers\SmsServiceController::class);
    Route::resource('sms_text',\App\Http\Controllers\SmsTextController::class);
    Route::resource('region',\App\Http\Controllers\RegionController::class);

    Route::get('excel/export',[\App\Http\Controllers\PhoneNumberController::class,'export'])->name('phone.export');

});


//Auth::routes([
//    'register' => false, // Registration Routes...
//    'reset' => false, // Password Reset Routes...
//    'verify' => false, // Email Verification Routes...
//]);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/SmsText.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SmsText extends Model
{
    use HasFactory;
    public $timestamps=false;

    protected $table = 'sms_text';
    protected $fillable = [
        'text',
        'date',
    ];
}

app/Http/Controllers/SmsTextController.php
<?php

namespace App\Http\Controllers;

use App\Models\Region;
use App\Models\SmsService;
use App\Models\SmsText;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class SmsTextController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->from && $request->to){
            $sms_text = DB::table('sms_text as st')
                ->leftJoin('sms as s','s.text_id','=','st.id')
                ->whereBetween('s.date',[$request->from, $request->to.' 23:59:59'])
                ->select('st.*',DB::raw('COUNT(s.id) as sms'))
                ->groupBy('st.id')
                ->orderBy('st.id','desc')
                ->paginate(10);
            $from = $request->from;
            $to = $request->to;
        }else{
            $sms_text = DB::table('sms_text as st')
                ->leftJoin('sms as s','s.text_id','=','st.id')
                ->select('st.*',DB::raw('COUNT(s.id) as sms'))
                ->groupBy('st.id')
                ->orderBy('st.id','desc')
                ->paginate(10);
            $from = date('Y-m-d');
            $to = date('Y-m-d');
        }


        return view('admin.sms_text.index', compact('sms_text','from','to'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $sms_text = new SmsText;
        $sms_text->text = $request->text;
        $sms_text->save();

        return redirect()->route('sms_text.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        if ($request->search && $request->from && $request->to){
            $messages = DB::table('sms as s')
                ->join('phone_numbers as pn','pn.id','=','s.number_id')
                ->join('sms_services as ss','ss.id','=','s.service_id')
                ->join('sms_text as st','st.id','=','s.text_id')
                ->where('s.text_id','=',$id)
                ->where('s.text','like','%'.$request->search.'%')
                ->whereBetween('s.date',[$request->from, $request->to.' 23:59:59'])
                ->select('pn.number','st.text','s.date','s.status','ss.name')
                ->orderBy('s.date','desc')
                ->paginate(10);
            $search = $request->search;
            $from = $request->from;
            $to = $request->to;
        }else if ($request->from && $request->to){
            $messages = DB::table('sms as s')
                ->join('phone_numbers as pn','pn.id','=','s.number_id')
                ->join('sms_services as ss','ss.id','=','s.service_id')
                ->join('sms_text as st','st.id','=','s.text_id')
                ->where('s.text_id','=',$id)
                ->whereBetween('s.date',[$request->from, $request->to.' 23:59:59'])
                ->select('pn.number','st.text','s.date','s.status','ss.name')
                ->orderBy('s.date','desc')
                ->paginate(10);
            $search = $request->search;
            $from = $request->from;
            $to = $request->to;
        }else{
            $messages = DB::table('sms as s')
                ->join('phone_numbers as pn','pn.id','=','s.number_id')
                ->join('sms_services as ss','ss.id','=','s.service_id')
                ->join('sms_text as st','st.id','=','s.text_id')
                ->where('s.text_id','=',$id)
                ->select('pn.number','st.text','s.date','s.status','ss.name')
                ->orderBy('s.date','desc')
                ->paginate(10);
            $search = '';
            $from = date('Y-m-d');
            $to = date('Y-m-d');
        }

        ///// sms controller index  ////

        if ($request->per_page){
            $per_page = $request->per_page;
        }else{
            $per_page = 10;
        }

        if ($request->search && $request->region != 0){
            $phones = DB::table('phone_numbers as pn')
                ->join('regions as r','r.id','=','pn.region_id')
                ->leftJoin('sms as s','s.number_id','=','pn.id')
                ->where('pn.number','like','%'.$request->search.'%')
                ->where('pn.region_id','=',$request->region)
                ->select('pn.*','r.name as region',
                    DB::raw('COUNT(s.id) as count'))
                ->groupBy('pn.id')
                ->paginate($per_page);
            $search = $request->search;
        }elseif ($request->search){
            $phones = DB::table('phone_numbers as pn')
                ->join('regions as r','r.id','=','pn.region_id')
                ->leftJoin('sms as s','s.number_id','=','pn.id')
                ->where('pn.number','like','%'.$request->search.'%')
                ->select('pn.*','r.name as region',
                    DB::raw('COUNT(s.id) as count'))
                ->groupBy('pn.id')
                ->paginate($per_page);
            $search = $request->search;
        }elseif ($request->region != 0){
            $phones = DB::table('phone_numbers as pn')
                ->join('regions as r','r.id','=','pn.region_id')
                ->leftJoin('sms as s','s.number_id','=','pn.id')
                ->where('pn.region_id','=',$request->region)
                ->select('pn.*','r.name as region',
                    DB::raw('COUNT(s.id) as count'))
                ->groupBy('pn.id')
                ->paginate($per_page);
            $search = '';
        }else{
            $phones = DB::table('phone_numbers as pn')
                ->join('regions as r','r.id','=','pn.region_id')
                ->leftJoin('sms as s','s.number_id','=','pn.id')
                ->select('pn.*','r.name as region',
                    DB::raw('COUNT(s.id) as count'))
                ->groupBy('pn.id')
                ->paginate($per_page);
            $search = '';

        }

        $region_id = $request->region;
        $regions = Region::all();
        $sms_services = SmsService::all();
        $sms_text = SmsText::all();


        return view('admin.sms_text.show',compact('messages','id','search','from','to',
            'phones','regions','region_id','per_page','sms_services','sms_text','id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'text'=>'required'
        ]);

        $sms_text = SmsText::find($id);
        $sms_text->text = $request->text;
        $sms_text->update();

        return redirect()->route('sms_text.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sms_text_ = SmsText::find($id);
        $sms_text = DB::table('sms_text as st')
            ->leftJoin('sms as s','s.text_id','=','st.id')
            ->select('st.*',DB::raw('COUNT(s.id) as sms'))
            ->where('st.id','=',$id)
            ->groupBy('st.id')
            ->first();
        if ($sms_text->sms == 0){
            $sms_text_->delete();
        }

        return redirect()->route('sms_text.index');
    }
}

resources/views/admin/sms_text/index.blade.php
@extends('layouts.main')
@section('main-content')

    <!-- /.card -->

    <div class="card">
        <div class="card-header">
            <ul class="navbar list-unstyled m-0 p-0">
                <li>
                    <h3 class="card-title">SMS Xizmatlar</h3>
                </li>
                <li>
                    <!-- SEARCH FORM -->
                    <form action="{{ route('sms_text.index') }}" method="get" class="form-inline m-0 ml-md-3">
                        @csrf

                        <div class="input-group input-group-sm">
                            <input name="from" value="{{$from}}" class="form-control form-control-navbar" type="date" >
                            <input name="to" value="{{$to}}" class="form-control form-control-navbar" type="date" >
                        </div>

                        <div class="input-group input-group-sm">
                            <div class="input-group-append">
                                <button class="btn btn-success" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </li>
            </ul>
        </div>
        <!-- /.card-header -->
        <div class="card-body pt-0 table-responsive">
            <table id="example1" class="table table-bordered table-striped ">
                <thead>
                <tr>
                    <th class="py-1">N</th>
                    <th class="py-1">Text</th>
                    <th class="py-1">Vaqt</th>
                    <th class="py-1">Sms</th>
                    <th class="py-1">
                        Action
                        <button type="button" class="btn btn-success my-0 py-0 px-1 " data-toggle="modal" data-target="#create-sms-text">
                            <i class="fas fa-plus m-0 p-0"></i>
                        </button>
                        <div class="modal fade" id="create-sms-text">
                            <div class="modal-dialog">
                                <div class="modal-content bg-primary">
                                    <form action="{{ route('sms_text.store') }}" method="post" enctype="multipart/form-data">

                                        <div class="modal-header">
                                            <h4 class="modal-title">Text yaratish</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">

                                            @csrf
                                            @method('post')
                                            <div class="card-body">
                                                <div class="form-group">
                                                    <label for="exampleInputEmail1">Text</label>
                                                    <textarea name="text" id="" cols="30" class="form-control" placeholder="Text kiriting"></textarea>
                                                </div>


                                                <div class="form-check">
                                                    <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                                                    <label class="form-check-label" for="exampleCheck1">Tekshirish</label>
                                                </div>
                                            </div>
                                            <!-- /.card-body -->
                                        </div>
                                        <div class="modal-footer justify-content-between">
                                            <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-outline-light">Saqlash</button>
                                        </div>

                                    </form>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>
                        <!-- /.modal -->
                    </th>
                </tr>
            </thead>


                    <tbody>
                @foreach($sms_text as $item)
                    <tr>
                        <td class="py-1">
                            {{($sms_text->currentpage()-1)*$sms_text->perpage()+($loop->index+1)}}
                        </td>
                        <td class="py-1">
                            <a href="{{ route('sms_text.show',$item->id) }}">{{ $item->text }}</a>
                        </td>
                        <td class="py-1">{{ $item->date }}</td>
                        <td class="py-1">{{ $item->sms }}</td>
                        <td class="py-1">

                            @if($item->sms == 0)

                            <button type="button" class="btn btn-danger my-0 py-0 px-1" data-toggle="modal" data-target="#modal-danger{{ $item->id }}">
                                <i class="fas fa-trash m-0 p-0"></i>
                            </button>

                            <div class="modal fade" id="modal-danger{{ $item->id }}">
                                <div class="modal-dialog">
                                    <div class="modal-content bg-danger">
                                        <div class="modal-header">
                                            <h4 class="modal-title">O'chirish</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>O'chirishni xohlaysizmi?</p>
                                        </div>
                                        <div class="modal-footer justify-content-between">
                                            <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                                            <form class="d-inline" action="{{ route('sms_text.destroy',$item->id) }}" method="post">
                                                @csrf
                                                @method('delete')
                                                <button type="submit" class="btn btn-outline-light">
                                                    O'chirish
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->


                            <button type="button" class="btn btn-info my-0 py-0 px-1 " data-toggle="modal" data-target="#modal{{ $loop->index+1 }}">
                                <i class="fas fa-edit m-0 p-0"></i>
                            </button>
                            <div class="modal fade" id="modal{{ $loop->index+1 }}">
                                <div class="modal-dialog">
                                    <div class="modal-content bg-primary">
                                        <form action="{{ route('sms_text.update', $item->id) }}" method="post" enctype="multipart/form-data">

                                            <div class="modal-header">
                                                <h4 class="modal-title">{{ $item->text }}</h4>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">

                                                @csrf
                                                @method('PUT')
                                                <div class="card-body">
                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1">Text</label>
                                                        <input name="text" type="text" class="form-control" value="{{ $item->text }}" placeholder="Text kiriting">
                                                    </div>


                                                    <div class="form-check">
                                                        <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                                                        <label class="form-check-label" for="exampleCheck1">Tekshirish</label>
                                                    </div>
                                                </div>
                                                <!-- /.card-body -->
                                            </div>
                                            <div class="modal-footer justify-content-between">
                                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-outline-light">Saqlash</button>
                                            </div>

                                        </form>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!-- /.modal -->
                            @endif

                        </td>
                    </tr>
                @endforeach
            </tbody>


        </table>

        <div>{{ $sms_text->appends($_GET)->links() }}</div>
    </div>
@endsection