routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
//    return redirect()->route('login');
});

Route::middleware(['auth'])->group(function () {

    Route::get('index', function (){
        return view('index');
    })->name('home.index');

    ///// Super admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'super_admin'], function (){

        Route::resources([
            'admin'=>\App\Http\Controllers\AdminController::class]);

    });

    ///// Admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'admin'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'index', 'show','edit','update'
        ]);

    });

    ///// Manager routes /////
    Route::group(['prefix'=>'admin','middleware'=>'manager'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'show','edit','index'
        ]);

        Route::resource('buyer', \App\Http\Controllers\BuyerController::class)->only([
            'index'
        ]);
    });


    Route::resource('dashboard',\App\Http\Controllers\DashboardController::class);
    Route::resource('phone',\App\Http\Controllers\PhoneNumberController::class);
    Route::resource('sms',\App\Http\Controllers\SmsController::class);
    Route::resource('sms_service',\App\Http\Controllers\SmsServiceController::class);
    Route::resource('sms_text',\App\Http\Controllers\SmsTextController::class);
    Route::resource('region',\App\Http\Controllers\RegionController::class);

    Route::get('excel/export',[\App\Http\Controllers\PhoneNumberController::class,'export'])->name('phone.export');

});


//Auth::routes([
//    'register' => false, // Registration Routes...
//    'reset' => false, // Password Reset Routes...
//    'verify' => false, // Email Verification Routes...
//]);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/phone/show.blade.php
@extends('layouts.main')
@section('main-content')

    <!-- /.card -->

    <div class="card">
        <div class="card-header">
            <ul class="navbar list-unstyled m-0 p-0">
                <li>
                    <h3 class="card-title">Telefon raqam</h3>
                </li>
                <li>
                    <!-- SEARCH FORM -->
                    <form action="{{ route('phone.show', $id) }}" method="get" class="form-inline m-0 ml-md-3">
                        @csrf

                        <div class="input-group input-group-sm">
                            <input name="from" value="{{$from}}" class="form-control form-control-navbar" type="date" >
                            <input name="to" value="{{$to}}" class="form-control form-control-navbar" type="date" >
                        </div>

                        <div class="input-group input-group-sm">
                            <input name="search" value="{{$search}}" class="form-control form-control-navbar" type="search" placeholder="Qidirish" aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-success" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </li>
            </ul>
        </div>
        <!-- /.card-header -->
        <div class="card-body pt-0 table-responsive">
            <table id="example1" class="table table-bordered table-striped ">
                <thead>
                <tr>
                    <th class="py-1">N</th>
                    <th class="py-1">Tel nomer</th>
                    <th class="py-1">Text</th>
                    <th class="py-1">Vaqt</th>
                    <th class="py-1">Sms xizmat</th>
                </tr>
            </thead>


                    <tbody>
                @foreach($messages as $message)
                    <tr>
                        <td class="py-1">
                            {{($messages->currentpage()-1)*$messages->perpage()+($loop->index+1)}}
                        </td>
                        <td class="py-1">{{ $message->number }}</td>
                        <td class="py-1">{{ $message->text }}</td>
                        <td class="py-1">{{ $message->date }}</td>
                        <td class="py-1">{{ $message->name }}</td>
                    </tr>
                @endforeach
            </tbody>


        </table>

        <div>{{ $messages->appends($_GET)->links() }}</div>
    </div>
@endsection